Artem
panchill/Startup-analytics pull request #3
Opened 2024-09-12 15:18 UTC by panchill

Добавил 2 графика (барплот и пайплот), также доделал групировку по проектам

2024-09-12 15:21 UTC, Arity-T commented
Назови нормально pr что ты тут вообще сделал

2024-09-12 15:38 UTC, Arity-T requested changes
1. Добавить requirements.txt
2. Не используй абсолютные пути
3. The function "set" is deprecated
  Function `set` is deprecated in favor of `set_theme`
4. На графике "Зависимость количество голосов от даты" мало что понятно, сделай скользящее среднее например
5. После графиков добавить какие-то выводы
6. Научись делать заголовки (см. markdown)
7. Мне кажется разбивка работает плохо, там почти всё должно быть IT. К тому же слишком много "Не определено".
8. Добавить вывод примеров стартапов из каждой категории
9.  PieChart слишком большой, неудобно смотреть
10. Определить точнее, что подразумевается под категориями. Обосновать выбор ключевых слов примерами из данных
11. Общие метрики надо выводить с подписями.

Ноутбук должен быть красиво и понятно оформлен, большие куски кода лучше вынести в отдельный файл/файлы, а потом подключить (import)

2024-09-13 09:28 UTC, panchill commented
> 1. Добавить requirements.txt
> 2. Не используй абсолютные пути
> 3. The function "set" is deprecated
>    Function `set` is deprecated in favor of `set_theme`
> 4. На графике "Зависимость количество голосов от даты" мало что понятно, сделай скользящее среднее например
> 5. После графиков добавить какие-то выводы
> 6. Научись делать заголовки (см. markdown)
> 7. Мне кажется разбивка работает плохо, там почти всё должно быть IT. К тому же слишком много "Не определено".
> 8. Добавить вывод примеров стартапов из каждой категории
> 9. PieChart слишком большой, неудобно смотреть
> 10. Определить точнее, что подразумевается под категориями. Обосновать выбор ключевых слов примерами из данных
> 11. Общие метрики надо выводить с подписями.
> 
> Ноутбук должен быть красиво и понятно оформлен, большие куски кода лучше вынести в отдельный файл/файлы, а потом подключить (import)

Смотреть самую последнюю версию (little fix)

2024-09-13 15:34 UTC, Arity-T requested changes
1. Что за файл pyenv.cfg. В репе его точно быть не должно.
2. Непонятная таблица по основным метрикам
3. 1 доллар != 1 рублю
4. Параметры скользящего среднего выведи на графике
5. Почему сначала идёт график, а только потом заголовок раздела и описание графика?
6. Не надо описывать график, я ведь его итак вижу, надо делать из него выводы или предположения и их записывать. Причём предположения можно сразу проверять. В тому же слово "вырасло", пишется через о
7. График с кол-вом стартапов по категориям слишком высокий, неудобно смотреть
8. Функции и большие куски кода вынести в отдельные файлы
9. История комитов должна быть понятна. В этом случае, я расписал, что нужно сделать, каждый комит должен, например, соответствовать одному пункту.

Пункты 7, 9, 10 из прошлого ревью актуальны

2024-09-13 15:51 UTC, panchill commented
> 1. Что за файл pyenv.cfg. В репе его точно быть не должно.
> 2. Непонятная таблица по основным метрикам
> 3. 1 доллар != 1 рублю
> 4. Параметры скользящего среднего выведи на графике
> 5. Почему сначала идёт график, а только потом заголовок раздела и описание графика?
> 6. Не надо описывать график, я ведь его итак вижу, надо делать из него выводы или предположения и их записывать. Причём предположения можно сразу проверять. В тому же слово "вырасло", пишется через о
> 7. График с кол-вом стартапов по категориям слишком высокий, неудобно смотреть
> 8. Функции и большие куски кода вынести в отдельные файлы
> 9. История комитов должна быть понятна. В этом случае, я расписал, что нужно сделать, каждый комит должен, например, соответствовать одному пункту.
> 
> Пункты 7, 9, 10 из прошлого ревью актуальны

Пункт 8 и пункт 9 из предыдущего комментария неактуальны

2024-09-15 09:22 UTC, Arity-T requested changes
1. Нет выводов по метрикам. Зачем их считали? Минимум 0 в инвестициях? 
2. Зачем первый график выведен в отдельный раздел, у которого заголовок совпадает с заголовком графика? Можно отнести к метрикам или к чему-то ещё. Тут снова вопрос, зачем мы его выводим.
3. > Из графика видно, что опросы стали проводиться примерно осенью 2019 года. Можно предположить, что выпуски начали выходить примерно в то же время.
Зачем предполагать то, что проверяется за полминуты? Вообщем-то каких-либо выводов со смысловой нагрузкой под графиком нет. Про ненужность описания графика словами уже говорил.
4. Обосновать неочевидный выбор ключевых слов в некоторых местах. Можно прокомментировать в коде.
5. >Для разбивки используются ключевые слова, которые наиболее подходят для выбраной категории. Слова выбирались по принципу запроса "топ-10 слов на тему "нужная тема", затем был проведен осмотр на наличие и удаление общих слов (слов с общими корнями, по типу "авто"), также переработан подход к парсингу: теперь слова в описании должны НАЧИНАТЬСЯ с ключевых слов, а не просто содержать корни в любом месте слова. После этого был проведен вторичный осмотр на "откровенно" ложные данные. Поскольку изначально не стоит задача идеально распределить все стартапы, а лишь раздеить их "условные" группы, основываясь на вторичную проверку, а также на получившиеся графики, можно сделать вывод о том, что IT - как и ожидалось, имеет наибольшую долю
Первое предложение бессмысленно. Куда были запросы? Зачем информация о том, что был переработан подход? Почему не стоит задача "идеально распределить все стартапы"? Какая тогда задача стоит и для чего? IT нет в категориях.
6. Все тексты либо перечитай сам, либо загони в ChatGPT и спроси, есть ли ошибки и опечатки, потому они почти везде, сложно читать.
7. Используй список (в markdown они встроены), а не заголовки, при перечислении категорий.
8. Посмотрел раздел с примерами. Хорошо бы добавить столбец с ключевыми словами, на основании которых стартап был отнесён к категории. Так будет легче оценить полезность ключевых слов.
9. Категории в основном хорошие, классифицируется нормально. Нужно переработать "Транспорт_и_доставка", например, выделить отдельно доставку, иначе  мешанина получается. С категорией "Кулинория" тоже надо порабоать, может быть переименовать. Нормального определения нет.
10. Используй один термин везде. Сейчас где-то "группы", а где-то "категории".
11. > Наиболее популярные категории в порядке убывания
Заголовок не подходит. Ты ведь выводишь все категории. К тому же вывод некрасивый, сделай таблицей.
12. > Количество стартапов по категориям
Подписи столбцов съехали.
13. Что попадает в категорию "Прочее"? Это самая большая категория, а ты её никак не анализируешь.
14. Убери лишние отсутпы в начале и конец ячеек с кодом и с markdown.

2024-09-16 21:11 UTC, panchill commented
> 1. Нет выводов по метрикам. Зачем их считали? Минимум 0 в инвестициях?
> 2. Зачем первый график выведен в отдельный раздел, у которого заголовок совпадает с заголовком графика? Можно отнести к метрикам или к чему-то ещё. Тут снова вопрос, зачем мы его выводим.
> 3. _Из графика видно, что опросы стали проводиться примерно осенью 2019 года. Можно предположить, что выпуски начали выходить примерно в то же время._
>    Зачем предполагать то, что проверяется за полминуты? Вообщем-то каких-либо выводов со смысловой нагрузкой под графиком нет. Про ненужность описания графика словами уже говорил.
> 4. Обосновать неочевидный выбор ключевых слов в некоторых местах. Можно прокомментировать в коде.
> 5. _Для разбивки используются ключевые слова, которые наиболее подходят для выбраной категории. Слова выбирались по принципу запроса "топ-10 слов на тему "нужная тема", затем был проведен осмотр на наличие и удаление общих слов (слов с общими корнями, по типу "авто"), также переработан подход к парсингу: теперь слова в описании должны НАЧИНАТЬСЯ с ключевых слов, а не просто содержать корни в любом месте слова. После этого был проведен вторичный осмотр на "откровенно" ложные данные. Поскольку изначально не стоит задача идеально распределить все стартапы, а лишь раздеить их "условные" группы, основываясь на вторичную проверку, а также на получившиеся графики, можно сделать вывод о том, что IT - как и ожидалось, имеет наибольшую долю_
>    Первое предложение бессмысленно. Куда были запросы? Зачем информация о том, что был переработан подход? Почему не стоит задача "идеально распределить все стартапы"? Какая тогда задача стоит и для чего? IT нет в категориях.
> 6. Все тексты либо перечитай сам, либо загони в ChatGPT и спроси, есть ли ошибки и опечатки, потому они почти везде, сложно читать.
> 7. Используй список (в markdown они встроены), а не заголовки, при перечислении категорий.
> 8. Посмотрел раздел с примерами. Хорошо бы добавить столбец с ключевыми словами, на основании которых стартап был отнесён к категории. Так будет легче оценить полезность ключевых слов.
> 9. Категории в основном хорошие, классифицируется нормально. Нужно переработать "Транспорт_и_доставка", например, выделить отдельно доставку, иначе  мешанина получается. С категорией "Кулинория" тоже надо порабоать, может быть переименовать. Нормального определения нет.
> 10. Используй один термин везде. Сейчас где-то "группы", а где-то "категории".
> 11. _Наиболее популярные категории в порядке убывания_
>     Заголовок не подходит. Ты ведь выводишь все категории. К тому же вывод некрасивый, сделай таблицей.
> 12. _Количество стартапов по категориям_
>     Подписи столбцов съехали.
> 13. Что попадает в категорию "Прочее"? Это самая большая категория, а ты её никак не анализируешь.
> 14. Убери лишние отсутпы в начале и конец ячеек с кодом и с markdown.

Пункт 10 выполнен

2024-09-18 12:13 UTC, Arity-T requested changes
1. Неактуальный комментарий про ключевое слово бот
2. Подумать про добавление категорий: фин-тех, маркетплейсы, HR (найм),
3. Ошибки при категоризации, они всё равно будут, но раз уж заметил, можно улучшить
Это про взаимоотношения
![image](https://github.com/user-attachments/assets/21460a4f-823c-4e60-8e28-4989873f1b0c)
Транспорт (как минимум слово автозапчасти и не только)
![image](https://github.com/user-attachments/assets/993192af-26b1-4cd6-aa17-510e256b3d87)

4. Крипта и инвестиции - возможно стоит разделить на две категории. Сейчас слова связанные с инвестициями не используются.
![image](https://github.com/user-attachments/assets/9334a913-da11-49ba-b492-a52b85f1b74a)

5. Из 10 стартапов в категории "Маркетинг и реклама" действительно к маркетингу и рекламе относятся только 3 - надо что-то с этим делать

6. Непонятно что означает категория "Роботы"

7. Про категорию "Прочее" до сих пор ничего непонятно, выведи примеры из неё, что ещё за стартапы с уникальными примерами.

2024-09-25 14:40 UTC, Arity-T requested changes
Мультикатегории исчезли, везде теперь по одной категории, это неправильно

2024-09-26 15:13 UTC, merged